name: 'Build .NET'
description: 'Build .NET for Umbraco V10'
inputs:
  organization-name:
    required: true
  project-name:
    required: true
  build-configuration:
    required: true
    default: 'release'
  csproj-path:
    required: true
  token:
    description: 'A Github PAT'
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name : Setup Nuget
      uses: nuget/setup-nuget@v1.0.6

    - name: Restore nuget packages
      run: nuget restore ${{ inputs.csproj-path }}
      shell: powershell

    - name: Build Solution
      run: msbuild ${{ inputs.csproj-path }} /nologo /nr:false /p:DeployOnBuild=true /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:AutoParameterizationWebConfigConnectionStrings=false /p:MvcBuildViews=false
      shell: powershell

    - name: Transform web.config
      run: |
        $webFolderExists = Test-Path .\*.web\
        if($webFolderExists){ cd .\*.web\ } else { cd .\*.site\ }
        $webBambooConfigExists = Test-Path web.live.config
        if($webBambooConfigExists) {c:\.\DeploymentScripts\ConfigTransformationTool\ctt.exe s:web.config t:web.bamboo.config d:web.config pw}
      shell: powershell

    - name: Copy files to sites folder
      run: |
        md -Force "${{ github.workspace }}/Archive/${{ inputs.organization-name }}/${{ inputs.project-name }}/${{ github.ref_name }}"
         $webFolderExists = Test-Path .\*.web\
         if($webFolderExists){Copy-Item .\*.Web\* "${{ github.workspace }}/Archive/${{ inputs.organization-name }}/${{ inputs.project-name }}/${{ github.ref_name }}" -force -recurse}
         if(-not $webFolderExists){Copy-Item .\*.Site\* "${{ github.workspace }}/Archive/${{ inputs.organization-name }}/${{ inputs.project-name }}/${{ github.ref_name }}" -force -recurse}
      shell: powershell
