name: 'Build .NET'
description: 'Build .NET for Umbraco V9'
inputs:
  organization-name:
    required: true
  project-name:
    required: true
  build-configuration:
    required: true
    default: 'release'
  csproj-path:
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup . NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Restore dependencies
      run: dotnet restore
      shell: powershell
      
    - name: Build
      run: dotnet build --configuration ${{ inputs.build-configuration }}
      shell: powershell
