name: 'Build .NET'
description: 'Build .NET for Umbraco V10'
inputs:
  organization-name:
    required: true
  project-name:
    required: true
  build-configuration:
    required: true
    default: 'release'
  csproj-path:
    required: true
  token:
    description: 'A Github PAT'
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup . NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    
    - name: Add GitHub PAT to nuget.config
      run: (Get-Content -path .\NuGet.config -Raw) -replace '{PAT}','${{ inputs.token }}' | Set-Content -Path .\NuGet.config
      shell: powershell

    - name: Restore dependencies
      run: dotnet restore
      shell: powershell
      
    - name: Build
      run: dotnet build --configuration ${{ inputs.build-configuration }}
      shell: powershell
   
    - name: Publish
      run: dotnet publish "${{ inputs.csproj-path }}" --output "${{ github.workspace }}/Archive/${{ inputs.organization-name }}/${{ inputs.project-name }}/${{ github.ref_name }}" --configuration ${{ inputs.build-configuration }} /p:EnvironmentName=Production --no-restore --no-build
      shell: powershell
